/path_generator:
   ros__parameters:
      traj_type: "sin"
      sin_cycle: 18.85
      sin_amplitude: 4.0
      resulation: 0.05
      direction: 1
      generate_from_file: true
      path_folder: "/home/dwayne/workspace/navigation/nav2_ws/src/navigation/file"
      path_filename: "coor_record.txt"


/sim_robot:
   ros__parameters:
      origin_x: 0.0
      origin_y: 0.0
      origin_phi: -120.0
