global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 0.2
      publish_frequency: 0.2
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      # robot_radius: 0.32
      footprint: "[ [-0.05, 0.15], [0.40,0.15], [0.40,-0.15], [0.15,-0.15], [-0.05,-0.15] ]"
      footprint_padding: 0.05

      resolution: 0.05
      track_unknown_space: false # bke
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          sensor_frame: laser_scanner_link
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.2
          obstacle_max_range: 5.0
          obstacle_min_range: 0.2
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0
        inflation_radius: 2.0
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "orchard_map.yaml"

guided_hybrid_planner_flow:
  ros__parameters:
    shot_distance: 0.5
    steer_angle_segment_size: 3
    wheel_base: 0.3429
    cost_penalty: 3.0
    reverse_penalty: 5.0
    steering_change_penalty: 2.0
    steering_penalty: 1.2
    max_steer_angle: 27.0
    publish_serch_tree: false
    show_log: false
    serch_radius: 1.0

    smoother:
      max_iterations: 1000
      w_smooth: 0.1 # was 0.3
      w_data: 0.3 # was 0.2
      tolerance: 1e-10
      do_refinement: true
